[envs.default]
installer = "uv"

[envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"
dependencies = ["ruff==0.9.9"]

[envs.hatch-test]
extra-dependencies = [
  "pyfakefs",
]

[envs.types]
extra-dependencies = [
  "mypy",
  "pytest",
]
[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/dda tests}"

[envs.docs]
dependencies = [
  # https://github.com/mkdocstrings/mkdocstrings/discussions/743
  # https://github.com/mkdocstrings/mkdocstrings/issues/756
  "markdown @ git+https://github.com/Python-Markdown/markdown.git@e912575a903215ebafaeb0fecbdad079d998b9ba",
  "mkdocs~=1.6.1",
  "mkdocs-material~=9.6.11",
  # Plugins
  "mkdocs-minify-plugin~=0.8.0",
  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/181
  "mkdocs-git-revision-date-localized-plugin~=1.3.0",
  "mkdocs-glightbox~=0.4.0",
  "mkdocs-redirects~=1.2.2",
  "mkdocstrings-python~=1.16.10",
  # Extensions
  "mkdocs-click~=0.9.0",
  "pymdown-extensions~=10.14.3",
  "ruff==0.9.9",
  # Necessary for syntax highlighting in code blocks
  "pygments~=2.19.1",
  # Validation
  "linkchecker~=10.5.0",
]
[envs.docs.env-vars]
DDA_BUILDING_DOCS = "true"
SOURCE_DATE_EPOCH = "1580601600"
PYTHONUNBUFFERED = "1"
[envs.docs.scripts]
build = "mkdocs build --clean --strict {args}"
serve = "mkdocs serve --dev-addr localhost:8000 {args}"
validate = "linkchecker --config .linkcheckerrc site"
# https://github.com/linkchecker/linkchecker/issues/678
build-check = [
  "build --no-directory-urls",
  "validate",
]
