[envs.default]
installer = "uv"

[envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"
dependencies = ["ruff==0.9.9"]

[envs.hatch-test]
extra-dependencies = [
  "pyfakefs",
]

[envs.types]
extra-dependencies = [
  "mypy",
  "pytest",
]
[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/dda tests}"
